config/routes.php
<?php
/**
 * Routes configuration.
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * It's loaded within the context of `Application::routes()` method which
 * receives a `RouteBuilder` instance `$routes` as method argument.
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Http\Middleware\CsrfProtectionMiddleware;
use Cake\Routing\Route\DashedRoute;
use Cake\Routing\RouteBuilder;

/*
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 */
/** @var \Cake\Routing\RouteBuilder $routes */
$routes->setRouteClass(DashedRoute::class);

$routes->scope('/', function (RouteBuilder $builder) {
    // Register scoped middleware for in scopes.
    $builder->registerMiddleware('csrf', new CsrfProtectionMiddleware([
        'httpOnly' => true,
    ]));

    /*
     * Apply a middleware to the current route scope.
     * Requires middleware to be registered through `Application::routes()` with `registerMiddleware()`
     */
    $builder->applyMiddleware('csrf');

    /*
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, templates/Pages/home.php)...
     */
    $builder->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);

    /*
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $builder->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /*
     * Connect catchall routes for all controllers.
     *
     * The `fallbacks` method is a shortcut for
     *
     * ```
     * $builder->connect('/:controller', ['action' => 'index']);
     * $builder->connect('/:controller/:action/*', []);
     * ```
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $builder->fallbacks();
});

/*
 * If you need a different set of middleware or none at all,
 * open new scope and define routes there.
 *
 * ```
 * $routes->scope('/api', function (RouteBuilder $builder) {
 *     // No $builder->applyMiddleware() here.
 *     // Connect API actions here.
 * });
 * ```
 */

src/Model/Table/AdictionalElementsHasPackagingCaffeeTable.php
<?php
declare(strict_types=1);

namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * AdictionalElementsHasPackagingCaffee Model
 *
 * @property \App\Model\Table\AdictionalElementsTable&\Cake\ORM\Association\BelongsTo $AdictionalElements
 * @property \App\Model\Table\InfoNavyTable&\Cake\ORM\Association\BelongsTo $InfoNavy
 *
 * @method \App\Model\Entity\AdictionalElementsHasPackagingCaffee newEmptyEntity()
 * @method \App\Model\Entity\AdictionalElementsHasPackagingCaffee newEntity(array $data, array $options = [])
 * @method \App\Model\Entity\AdictionalElementsHasPackagingCaffee[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\AdictionalElementsHasPackagingCaffee get($primaryKey, $options = [])
 * @method \App\Model\Entity\AdictionalElementsHasPackagingCaffee findOrCreate($search, ?callable $callback = null, $options = [])
 * @method \App\Model\Entity\AdictionalElementsHasPackagingCaffee patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\AdictionalElementsHasPackagingCaffee[] patchEntities(iterable $entities, array $data, array $options = [])
 * @method \App\Model\Entity\AdictionalElementsHasPackagingCaffee|false save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\AdictionalElementsHasPackagingCaffee saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\AdictionalElementsHasPackagingCaffee[]|\Cake\Datasource\ResultSetInterface|false saveMany(iterable $entities, $options = [])
 * @method \App\Model\Entity\AdictionalElementsHasPackagingCaffee[]|\Cake\Datasource\ResultSetInterface saveManyOrFail(iterable $entities, $options = [])
 * @method \App\Model\Entity\AdictionalElementsHasPackagingCaffee[]|\Cake\Datasource\ResultSetInterface|false deleteMany(iterable $entities, $options = [])
 * @method \App\Model\Entity\AdictionalElementsHasPackagingCaffee[]|\Cake\Datasource\ResultSetInterface deleteManyOrFail(iterable $entities, $options = [])
 */
class AdictionalElementsHasPackagingCaffeeTable extends Table
{
    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config): void
    {
        parent::initialize($config);

        $this->setTable('adictional_elements_has_packaging_caffee');
        $this->setDisplayField('adictional_elements_id');
        $this->setPrimaryKey(['adictional_elements_id', 'info_navy_id']);

        $this->belongsTo('AdictionalElements', [
            'foreignKey' => 'adictional_elements_id',
            'joinType' => 'INNER',
        ]);
        $this->belongsTo('InfoNavy', [
            'foreignKey' => 'info_navy_id',
            'joinType' => 'INNER',
        ]);
        $this->belongsTo('SillcafUsers', [
            'foreignKey' => 'sillcaf_user_reg_id',
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator): Validator
    {
        $validator
            ->integer('quantity')
            ->requirePresence('quantity', 'create')
            ->notEmptyString('quantity');

        $validator
            ->scalar('type_unit')
            ->maxLength('type_unit', 45)
            ->requirePresence('type_unit', 'create')
            ->notEmptyString('type_unit');

        $validator
            ->scalar('observation')
            ->maxLength('observation', 200)
            ->allowEmptyString('observation');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules): RulesChecker
    {
        $rules->add($rules->existsIn(['adictional_elements_id'], 'AdictionalElements'));
        $rules->add($rules->existsIn(['info_navy_id'], 'InfoNavy'));
        $rules->add($rules->existsIn(['sillcaf_user_reg_id'], 'SillcafUsers'));

        return $rules;
    }
}

src/Controller/AdictionalElementsHasPackagingCaffeeController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use Cake\Log\Log;

/**
 * AdictionalElementsHasPackagingCaffee Controller
 *
 * @property \App\Model\Table\AdictionalElementsHasPackagingCaffeeTable $AdictionalElementsHasPackagingCaffee
 * @method \App\Model\Entity\AdictionalElementsHasPackagingCaffee[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class AdictionalElementsHasPackagingCaffeeController extends AppController
{

    public function isAuthorized($user)
    {
        if (in_array($this->request->getParam('action'), ['edit', 'delete'])) {
            if (in_array($user->read('SillcafUsers.sillcaf_perfile.id'), [2, 3])) {
                $this->loadModel('InfoNavy');
                $itemId = (int)$this->request->getParam('pass.1');
                $infoNavy = $this->InfoNavy->get($itemId);
                if ($infoNavy['navy_agent_id'] == $user->read('SillcafUsers.navyagent_user_id')) {
                    return true;
                } else if ($infoNavy['customs_id'] == $user->read('SillcafUsers.customs_user_id')) {
                    return true;
                } else {
                    $this->loadModel('SillcafInfonavyCustom');
                    $resultData = $this->SillcafInfonavyCustom->find('all')->where(['info_navy_id' => $itemId, 'custom_id' => $user->read('SillcafUsers.customs_user_id')]);
                    if ($resultData) {
                        return true;
                    }
                }
            }
        } else if (in_array($this->request->getParam('action'), ['add'])) {
            if (in_array($user->read('SillcafUsers.sillcaf_perfile.id'), [2, 3])) {
                $this->loadModel('InfoNavy');
                $itemId = (int)$this->request->getParam('pass.0');
                $infoNavy = $this->InfoNavy->get($itemId);
                if ($infoNavy['navy_agent_id'] == $user->read('SillcafUsers.navyagent_user_id')) {
                    return true;
                } else if ($infoNavy['customs_id'] == $user->read('SillcafUsers.customs_user_id')) {
                    return true;
                } else {
                    $this->loadModel('SillcafInfonavyCustom');
                    $resultData = $this->SillcafInfonavyCustom->find('all')->where(['info_navy_id' => $itemId, 'custom_id' => $user->read('SillcafUsers.customs_user_id')]);
                    if ($resultData) {
                        return true;
                    }
                }
            }
        }
        return parent::isAuthorized($user);
    }

    /**
     * Index method
     *
     * @return \Cake\Http\Response|null|void Renders view
     */
    public function index()
    {
        $session = $this->request->getSession();
        if (!$session->read('SillcafUsers.id')) {
            return $this->redirect(['controller' => 'sillcafUsers', 'action' => 'signin']);
        }
        $infoNavyId = $this->request->getQuery('infoNavyId');
        $this->loadModel('InfoNavy');
        $infoNavy = $this->InfoNavy->get($infoNavyId);
        $options = [
            'contain' => ['AdictionalElements', 'InfoNavy'],
        ];
        $adictionalElementsHasPackagingCaffee = $this->AdictionalElementsHasPackagingCaffee->find("all", $options)->where(['info_navy_id' => $infoNavyId]);

        $this->set(compact('adictionalElementsHasPackagingCaffee', 'infoNavy'));
    }

    /**
     * View method
     *
     * @param string|null $id Adictional Elements Has Packaging Caffee id.
     * @return \Cake\Http\Response|null|void Renders view
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $session = $this->request->getSession();
        if (!$session->read('SillcafUsers.id')) {
            return $this->redirect(['controller' => 'sillcafUsers', 'action' => 'signin']);
        }
        $adictionalElementsHasPackagingCaffee = $this->AdictionalElementsHasPackagingCaffee->get($id, [
            'contain' => ['AdictionalElements', 'InfoNavy'],
        ]);

        $this->set(compact('adictionalElementsHasPackagingCaffee'));
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null|void Redirects on successful add, renders view otherwise.
     */
    public function add($infoNavyId)
    {
        $session = $this->request->getSession();
        if (!$session->read('SillcafUsers.id')) {
            return $this->redirect(['controller' => 'sillcafUsers', 'action' => 'signin']);
        }
        if (!$this->isAuthorized($session)) {
            return $this->redirect(['controller' => 'sillcaf-users', 'action' => 'indicator']);
        }
        $adictionalElementsHasPackagingCaffee = $this->AdictionalElementsHasPackagingCaffee->newEmptyEntity();
        if ($this->request->is('post')) {
            $adictionalElementsHasPackagingCaffee = $this->AdictionalElementsHasPackagingCaffee->patchEntity($adictionalElementsHasPackagingCaffee, $this->request->getData());
            $adictionalElementsHasPackagingCaffee['adictional_elements_id'] = $this->request->getData()['adictional_elements_id'];
            $adictionalElementsHasPackagingCaffee['info_navy_id'] = $this->request->getData()['info_navy_id'];
            $adictionalElementsHasPackagingCaffee['sillcaf_user_reg_id'] = $this->request->getSession()->read('SillcafUsers.id');
            if ($this->AdictionalElementsHasPackagingCaffee->save($adictionalElementsHasPackagingCaffee)) {
                $this->Flash->success(__('Se ha guardado el elemento adicional con éxito'));

                return $this->redirect(['controller' => 'InfoNavy', 'action' => 'view', $adictionalElementsHasPackagingCaffee['info_navy_id']]);
            }
            $this->Flash->error(__('Se producido un error al guardae el elemento adicional, intente de nuevo'));
        }
        $adictionalElements = $this->AdictionalElementsHasPackagingCaffee->AdictionalElements->find('list', ['limit' => 200]);
        $infoNavy = $this->AdictionalElementsHasPackagingCaffee->InfoNavy->get($infoNavyId);
        $this->set(compact('adictionalElementsHasPackagingCaffee', 'adictionalElements', 'infoNavy'));
    }

    /**
     * Edit method
     *
     * @param string|null $id Adictional Elements Has Packaging Caffee id.
     * @return \Cake\Http\Response|null|void Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function edit($adictional_elements_id, $infoNavyId)
    {
        $session = $this->request->getSession();
        if (!$session->read('SillcafUsers.id')) {
            return $this->redirect(['controller' => 'sillcafUsers', 'action' => 'signin']);
        }
        if (!$this->isAuthorized($session)) {
            return $this->redirect(['controller' => 'sillcaf-users', 'action' => 'indicator']);
        }
        $adictionalElementsHasPackagingCaffee = $this->AdictionalElementsHasPackagingCaffee->find('all')->where(['adictional_elements_id' => $adictional_elements_id, 'info_navy_id' => $infoNavyId])->first();
        if ($this->request->is(['patch', 'post', 'put'])) {
            $adictionalElementsHasPackagingCaffee = $this->AdictionalElementsHasPackagingCaffee->patchEntity($adictionalElementsHasPackagingCaffee, $this->request->getData());
            if ($this->AdictionalElementsHasPackagingCaffee->save($adictionalElementsHasPackagingCaffee)) {
                $this->Flash->success(__('Se actualizó con exito el registro.'));

                return $this->redirect(['controller' => 'InfoNavy', 'action' => 'view', $adictionalElementsHasPackagingCaffee['info_navy_id']]);
            }
            $this->Flash->error(__('The adictional elements has packaging caffee could not be saved. Please, try again.'));
        }
        $adictionalElements = $this->AdictionalElementsHasPackagingCaffee->AdictionalElements->find('list', ['limit' => 200]);
        $infoNavy = $this->AdictionalElementsHasPackagingCaffee->InfoNavy->get($infoNavyId);
        $this->set(compact('adictionalElementsHasPackagingCaffee', 'adictionalElements', 'infoNavy'));
    }

    /**
     * Delete method
     *
     * @param string|null $id Adictional Elements Has Packaging Caffee id.
     * @return \Cake\Http\Response|null|void Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($adictional_elements_id, $infoNavyId)
    {
        $session = $this->request->getSession();
        if (!$session->read('SillcafUsers.id')) {
            return $this->redirect(['controller' => 'sillcafUsers', 'action' => 'signin']);
        }
        if (!$this->isAuthorized($session)) {
            return $this->redirect(['controller' => 'sillcaf-users', 'action' => 'indicator']);
        }
        $this->request->allowMethod(['post', 'delete']);
        $adictionalElementsHasPackagingCaffee = $this->AdictionalElementsHasPackagingCaffee->find('all')->where(['adictional_elements_id' => $adictional_elements_id, 'info_navy_id' => $infoNavyId])->first();
        if ($this->AdictionalElementsHasPackagingCaffee->delete($adictionalElementsHasPackagingCaffee)) {
            $this->Flash->success(__('Se elimino con exito el registro.'));
        } else {
            $this->Flash->error(__('The adictional elements has packaging caffee could not be deleted. Please, try again.'));
        }

        return $this->redirect(['controller' => 'InfoNavy', 'action' => 'view', $infoNavyId]);
    }
}

templates/AdictionalElementsHasPackagingCaffee/add.php
<?php

/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\AdictionalElementsHasPackagingCaffee $adictionalElementsHasPackagingCaffee
 */
?>
<div class="breadcrumb-header justify-content-between">
    <div class="my-auto">
        <div class="d-flex">
            <h4 class="content-title mb-0 my-auto">
                <?= $this->Html->link(__('Proformas'), ['controller' => 'InfoNavy', 'action' => 'index'], ['class' => 'side-nav-item']) ?>
                </h4><span class="text-muted mt-1 tx-13 ml-2 mb-0">  <?= $this->Html->link(__('/ Detalle proforma'), ['controller' => 'InfoNavy', 'action' => 'view',  $infoNavy['id']], ['class' => 'side-nav-item']) ?> </span><span class="text-muted mt-1 tx-13 ml-2 mb-0"> / Agregar</span>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-xl-12 col-xs-12 col-sm-12">
        <div class="card">
            <div class="card-body">
                <div class="col-lg">
                    <?= $this->Form->create($adictionalElementsHasPackagingCaffee) ?>
                    <fieldset>
                        <div class="row">
                            <div class="col-sm-8">
                                <legend><?= __('Agregar Elemento Adicional para la proforma ').$this->Html->link($infoNavy['proforma'], ['controller' => 'InfoNavy', 'action' => 'view',  $infoNavy['id']]) ?></legend>
                            </div>
                            <div class="col-sm-4"><?= $this->Form->button(__('Guardar'), ['class' => "btn btn-primary-gradient btn-block"]) ?></div>
                        </div>
                        <?php
                        echo $this->Form->control('info_navy_id', ['type' => 'hidden', 'value' => $infoNavy['id']]);
                        echo $this->Form->control('adictional_elements_id', [
                            'label' => 'Elemento adicional',
                            'type' => 'select',
                            'empty' => true,
                            'options' => $adictionalElements
                        ]);
                        echo $this->Form->control('quantity', ['label' => 'Cantidad']);
                        echo $this->Form->control('type_unit', [
                            'label' => 'Unidad',
                            'options' => array('CAPA' => 'CAPA', 'UNIDAD' => 'UNIDAD', 'N/A' => 'N/A'),
                            'empty' => true
                        ]);
                        echo $this->Form->control('observation', ['label' => 'Observación', 'type' => 'textarea']);
                        ?>
                    </fieldset>
                    <?= $this->Form->end() ?>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function() {
        $('#adictional-elements-id').select2({
            placeholder: 'Seleccione..',
            searchInputPlaceholder: 'Search'
        });
        $('#type-unit').select2({
            placeholder: 'Seleccione..',
            searchInputPlaceholder: 'Search'
        });
    });
</script>

templates/AdictionalElementsHasPackagingCaffee/edit.php
<?php

/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\AdictionalElementsHasPackagingCaffee $adictionalElementsHasPackagingCaffee
 */
?>
<div class="breadcrumb-header justify-content-between">
    <div class="my-auto">
        <div class="d-flex">
            <h4 class="content-title mb-0 my-auto">
                <?= $this->Html->link(__('Proformas'), ['controller' => 'InfoNavy', 'action' => 'index'], ['class' => 'side-nav-item']) ?>
                </h4><span class="text-muted mt-1 tx-13 ml-2 mb-0"> / <?= $this->Html->link(__('Detalle proforma'), ['controller' => 'InfoNavy', 'action' => 'view',  $infoNavy['id']], ['class' => 'side-nav-item']) ?> </span><span class="text-muted mt-1 tx-13 ml-2 mb-0"> / Agregar</span>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-xl-12 col-xs-12 col-sm-12">
        <div class="card">
            <div class="card-body">
                <div class="col-lg">
                    <?= $this->Form->create($adictionalElementsHasPackagingCaffee) ?>
                    <fieldset>
                        <div class="row">
                            <div class="col-sm-8">
                                <legend><?= __('Agregar Elemento Adicional para la proforma ').$this->Html->link($infoNavy['proforma'], ['controller' => 'InfoNavy', 'action' => 'view',  $infoNavy['id']]) ?></legend>
                            </div>
                            <div class="col-sm-4"><?= $this->Form->button(__('Guardar'), ['class' => "btn btn-primary-gradient btn-block"]) ?></div>
                        </div>
                        <?php
                        echo $this->Form->control('info_navy_id', ['type' => 'hidden', 'value' => $infoNavy['id']]);
                        echo $this->Form->control('adictional_elements_id', [
                            'label' => 'Elemento adicional',
                            'type' => 'select',
                            'value' => $adictionalElementsHasPackagingCaffee['adictional_elements_id'],
                            'empty' => true,
                            'disabled' => true,
                            'options' => $adictionalElements
                        ]);
                        echo $this->Form->control('quantity', ['label' => 'Cantidad']);
                        echo $this->Form->control('type_unit', [
                            'label' => 'Unidad',
                            'options' => array('CAPA' => 'CAPA', 'UNIDAD' => 'UNIDAD', 'N/A' => 'N/A'),
                            'empty' => true
                        ]);
                        echo $this->Form->control('observation', ['label' => 'Observación', 'type' => 'textarea']);
                        ?>
                    </fieldset>
                    <?= $this->Form->end() ?>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function() {
        $('#adictional-elements').select2({
            placeholder: 'Seleccione..',
            searchInputPlaceholder: 'Search'
        });
        $('#type-unit').select2({
            placeholder: 'Seleccione..',
            searchInputPlaceholder: 'Search'
        });
    });
</script>

templates/AdictionalElementsHasPackagingCaffee/index.php
<?php

/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\AdictionalElementsHasPackagingCaffee[]|\Cake\Collection\CollectionInterface $adictionalElementsHasPackagingCaffee
 */
?>

<div class="breadcrumb-header justify-content-between">
    <div class="my-auto">
        <div class="d-flex">
            <h3 class="content-title mb-0 my-auto">
                <?= $this->Html->link(__('Proformas'), ['controller' => 'InfoNavy', 'action' => 'index'], ['class' => 'side-nav-item']) ?>
            </h3><span class="text-muted mt-1 tx-13 ml-2 mb-0">/ Elementos Adicionales</span>
        </div>
    </div>
    <div class="d-flex my-xl-auto right-content">
        <div id="table_buttons" class="mb-3 mb-xl-0">
        </div>
    </div>
</div>

<div class="row row-sm">
    <div class="col-xl-12">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-8">
                        <legend>Elementos Adicionales de la proforma</legend>
                        <legend>ID sistema: <?= $infoNavy['id'] ?> | Proforma: <?= $infoNavy['proforma'] ?></legend>
                    </div>
                    <?php if ($infoNavy['status_info_navy_id'] == 1) { ?>
                        <div class="col-sm-4"><?= $this->Html->link(__('Nuevo Elemento'), ['action' => 'add', $infoNavy['id'], $infoNavy['proforma']], ['class' => "btn btn-primary-gradient btn-block"]) ?></div>
                    <?php } ?>
                </div>
                <div class="table-responsive">
                    <table class="table text-md-" id="tablaData">
                        <thead>
                            <tr>
                                <th>Elemento</th>
                                <th>Cantidad</th>
                                <th>Tipo de Unidad</th>
                                <th>Observaciones</th>
                                <th class="actions"><?= __('Actions') ?></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($adictionalElementsHasPackagingCaffee as $adictionalElementsHasPackagingCaffee) : ?>
                                <tr>
                                    <td><?= $adictionalElementsHasPackagingCaffee->adictional_element->name ?></td>
                                    <td><?= $this->Number->format($adictionalElementsHasPackagingCaffee->quantity) ?></td>
                                    <td><?= $adictionalElementsHasPackagingCaffee->type_unit ?></td>
                                    <td><?= $adictionalElementsHasPackagingCaffee->observation ?></td>
                                    <td class="actions">
                                        <?php if ($infoNavy['status_info_navy_id'] == 1) { ?>
                                            <?= $this->Html->link(
                                                $this->Html->tag('i', '', ['class' => 'side-menu__icon btn btn-sm btn-info far fa-edit']),
                                                ['action' => 'edit', $adictionalElementsHasPackagingCaffee->adictional_elements_id, $infoNavy['id'], $infoNavy['proforma']],
                                                ['escape' => false]
                                            ) ?>
                                            <?= $this->Form->postLink(
                                                $this->Html->tag('i', '', ['class' => 'side-menu__icon btn btn-sm btn-info far fa-trash']),
                                                ['action' => 'delete', $adictionalElementsHasPackagingCaffee->adictional_elements_id, $infoNavy['id'], $infoNavy['proforma']],
                                                ['escape' => false, 'confirm' => __('Está seguro de borrar este elemento?')]
                                            ); ?>
                                        <?php } ?>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function() {
        var table = $("#tablaData").DataTable({
            dom: 'Bfitp',
            buttons: [
                'pageLength', 'copy', 'excel', 'pdf',
                {
                    extend: 'colvis',
                    postfixButtons: ['colvisRestore']
                },
                {
                    text: 'Reload',
                    action: function(e, dt, node, config) {
                        dt.ajax.reload();
                    }
                }
            ],
            lengthMenu: [
                [10, 25, 50, -1],
                ['10 rows', '25 rows', '50 rows', 'Show all']
            ],
            language: {
                searchPlaceholder: 'Search...',
                sSearch: '',
                lengthMenu: '_MENU_ ',
            }
        });

        table.buttons().container()
            .appendTo('#table_buttons');

    });
</script>